package com.github.softwarearoma.dartutility.actions

import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.vfs.VirtualFile
import java.io.File

class GenerateIndexAction : AnAction() {

    override fun getActionUpdateThread(): ActionUpdateThread = ActionUpdateThread.BGT

    override fun actionPerformed(event: AnActionEvent) {
        // Get the selected virtual file (directory) in the Project view
        val folder: VirtualFile? = event.getData(CommonDataKeys.VIRTUAL_FILE)

        // Ensure the folder is not null and is indeed a directory
        if (folder != null && folder.isDirectory) {
            generateIndexFile(File(folder.path))
        }
    }

    private fun generateIndexFile(folder: File) {
        val dartFiles = folder.listFiles {
                file -> file.extension == "dart" && file.name != "index.dart" &&  !file.name.matches(Regex(".*\\..+\\.dart"))
        } ?: return
        val indexFile = File(folder, "index.dart")
        indexFile.writeText("") // clear the existing contents of the index.dart file
        indexFile.writeText(
            """
                /*
                 * AUTO-GENERATED FILE - DO NOT MODIFY
                 *
                 * Generated by Dart Utility Plugin
                 *
                 * This index file was created automatically to export Dart files
                 * within this directory.
                 *
                 * Excluded files:
                 *  - Generated files (*.g.dart)
                 *  - Freezed files (*.freezed.dart)
                 *  - Auto-route files (*.gr.dart)
                 *  - Test files (*_test.dart)
                 *  - Mock files (*.mocks.dart)
                 *
                 * Any manual changes to this file may be overwritten.
                 */
            """.trimIndent() + "\n\n"
        )
        dartFiles.forEach { file ->
            indexFile.appendText("export '${file.name}';\n")
        }
    }
}